template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "kich1262"
__REPO__ = "lang-quc-x-ext-apertium"
__UND2C__ = "quc"
__UNDEFINED__ = "K'iche'"
__UND__ = "quc"
