template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "kich1262"
__REPO__ = "lang-quc-x-ext-apertium"
__UND2C__ = "quc"
__UNDEFINED__ = "K'iche'"
__UND__ = "quc"
