template = "https://github.com/giellalt/template-lang-und"
rev_id = 285
template_sha = "dc60d9e35b17842271a5a82c114510f9ff1a3d72"

[replacements]
__GLOTTOLOG_ID__ = "kich1262"
__REPO__ = "lang-quc-x-ext-apertium"
__UND2C__ = "quc"
__UNDEFINED__ = "K'iche'"
__UND__ = "quc"
